const ac=[
    {
        acid: 1,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        type: 'Tropical Constant Speed Type',
        model: 'RAS-S18HPA + RAC-S18HPA',
        capacity: ' 1.5 Ton',
        submodel: 'R22',
        heating: true,
        system: 'heating & cooling',
        price: 54000,
        img1: 'https://i.ibb.co/BgsWhvL/1.png',
        img2: '',
        img3: '',
        features: [
            'DC Power System (Safe and Efficient)',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1φ/50Hz/220-240V',
            Capacity: '5.30kW / 5.36kW',
            TotalInput: '1,990-2,020W / 1,600-1,710 W',
            TotalAmperes: '8.80-8.70A / 7.50-7.50A',
            EER: '9.52-8.95Btu/h.W / 11.43-10.70Btu/h.W',
            COP: '2.79-2.62 / 3.35-3.13',
            StartingCurrent: '49A',
            AirFlow: '17.5/ 15.3/ 12.5/ 11.0 m3/min',
            DehumidifyingCapacity: '2.8 L/h',
            PipeSize: '6.35mm / 12.7mm',
            DimensionIndoor: '900 x 300 x 230 mm',
            DimensionOutdoor: '750 x 570 x 280 mm',
            WeightIndoor: '11kg',
            WeightOutdoor: '38kg'
        }
    },
    {
        acid: 2,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type: 'Tropical Constant Speed Type',
        type1: 'split',
        model: 'RAS-S24HPA (RAC-S24HPA)',
        capacity: '2.0 Ton',
        submodel: 'R22',
        heating: true,
        system: 'heating & cooling',
        price: 64000,
        img1: 'https://i.ibb.co/pfGGg8Q/2.png',
        img2: '',
        img3: '',
        features: [
            'DC Power System (Safe and Efficient)',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode',
            'Auto Restart',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1φ/50Hz/220-240V',
            Capacity: '7.04kW / 7.05kW',
            TotalInput: '2,265-2,400W/ 2,365-2,540W',
            TotalAmperes: '10.8-10.50A / 11.40-11.20A',
            EER: '10.61-10.01Btu/h.W / 10.17-9.47Btu/h.W',
            COP: '3.11-2.93 / 2.98-2.78',
            StartingCurrent: '60 A',
            AirFlow: '18.4/ 17.5/ 12.0/ 9.8 m3/min',
            DehumidifyingCapacity: '2.8 L/h',
            PipeSize: '6.35mm / 15.88mm',
            DimensionIndoor: '900 x 300 x 230 mm',
            DimensionOutdoor: '850 x 650 x 298 mm',
            WeightIndoor: '11kg',
            WeightOutdoor: '52kg'
        }
    },
    {
        acid: 3,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        type: 'Tropical Constant Speed Type',
        model: 'RAS-F13CF / RAC-F13CF',
        capacity: '1.0 Ton',
        submodel: 'R410A',
        heating: false,
        system: 'Cooling',
        price: 38000,
        img1: 'https://i.ibb.co/vZKpbkG/3.png',
        img2: '',
        img3: '',
        features: [
            'DC Power System (Safe and Efficient)',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1φ/50Hz/220-230V',
            Capacity: '3.50-3.52kW',
            TotalInput: '1,230-1,250W',
            TotalAmperes: '5.70-5.54A',
            EER: '9.72-9.62Btu/h.W',
            COP: '2.85-2.82',
            StartingCurrent: '27 A',
            AirFlow: '12.0/10.5/8.5/6.0 (HH/H/M/L/Sl)m3/min ',
            DehumidifyingCapacity: '2.8 l/h',
            PipeSize: '6.35/12.7mm',
            DimensionIndoor: '790 x 300 x 230 mm',
            DimensionOutdoor: '750 x 570 x 280 mm',
            WeightIndoor: '9.5kg',
            WeightOutdoor: '31.5kg'
        }
    },
    {
        acid: 4,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        type: 'Tropical Constant Speed Type',
        model: 'RAS-F18CF/RAC-F18CF',
        capacity: '1.5 Ton',
        submodel: 'R410a',
        heating: false,
        system: 'Cooling',
        price: 55000,
        img1: 'https://i.ibb.co/ChGzSsJ/4.png',
        img2: '',
        img3: '',
        features: [
            'DC Power System (Safe and Efficient)',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode',
            'Auto Restart',
            'Sensor Dry',
            'Silent Mode',
            'Up-Down Auto Swing',
            'Anti-Rust Outdoor Casing',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1Ø, 220-230V, 50Hz',
            Capacity: '5.5kW, 18000 BTU/h',
            TotalInput: '1600W',
            TotalAmperes: '7.1A',
            EER: '9.72-9.62Btu/h.W',
            COP: '2.85-2.82',
            StartingCurrent: '27 A',
            AirFlow: '18.0/16.5/12.5/10.5/7.5㎥ (Powerful/H/M/L/S) ',
            DehumidifyingCapacity: '3.5l/h',
            PipeSize: 'Diameter (Liquid/Gas): 6.35/ 12.7mm Maximum Length/ Height: 20/10m',
            DimensionIndoor: '1,100 × 300 × 260mm ',
            DimensionOutdoor: '850 × 650 × 298mm',
            WeightIndoor: '14.5kg',
            WeightOutdoor: '44kg'
        }
    },
    {
        acid: 5,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        type: 'Tropical Constant Speed Type',
        model: 'RAS-F24CF/RAC-F24CF',
        capacity: '2.0 Ton',
        submodel: 'R410a',
        heating: false,
        system: 'Cooling',
        price: 65000,
        img1: 'https://i.ibb.co/6Yvrx83/5.png',
        img2: '',
        img3: '',
        features: [
            'DC Power System (Safe and Efficient)',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode',
            'Auto Restart',
            'Sensor Dry',
            'Silent Mode',
            'Up-Down Auto Swing',
            'Anti-Rust Outdoor Casing',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1Ø, 220-230V, 50Hz',
            Capacity: '5.5kW, 18000 BTU/h',
            TotalInput: '1600W',
            TotalAmperes: '7.1A',
            EER: '9.72-9.62Btu/h.W',
            COP: '2.85-2.82',
            StartingCurrent: '27 A',
            AirFlow: '18.0/16.5/12.5/10.5/7.5㎥ (Powerful/H/M/L/S) ',
            DehumidifyingCapacity: '3.5l/h',
            PipeSize: 'Diameter (Liquid/Gas): 6.35/ 12.7mm Maximum Length/ Height: 20/10m',
            DimensionIndoor: '1,100 × 300 × 260mm ',
            DimensionOutdoor: '850 × 650 × 298mm',
            WeightIndoor: '14.5kg',
            WeightOutdoor: '44kg'
        }
    },
    {
        acid: 6,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        type: 'Tropical Constant Speed Type',
        model: 'RAS-S30CPZ (RAC-S30CPZ)',
        capacity: '2.5 Ton',
        submodel: 'R22',
        heating: false,
        system: 'Cooling',
        price: 70000,
        img1: 'https://i.ibb.co/bgDFzPV/6.png',
        img2: '',
        img3: '',
        features: [
            'Removeable, washable panel',
            'Automatic shift of fan speed',
            'Air flow direction',
            'Remote controller timer',
            'LED self diagnosis',
            'Air purifying filter',
            'DC Power System (Safe and Efficient)',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode Control',
            'Auto Restart',
            'Sensor Dry',
            'Pre filter',
            'Silent Mode',
            'Up-Down Auto Swing',
            'Anti corrosion coating on outdoor condenser',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1ph / 50Hz/AC 220-240V',
            Capacity: '8.55 ～ 8.65kW',
            TotalInput: '3.0 ～ 3.13kW',
            TotalAmperes: '7.1A',
            EER: '9.72 ～ 9.43 / - Btu / h.W',
            COP: '2.85 ～ 2.76 / -',
            StartingCurrent: '83.0 A',
            AirFlow: '18.0 / 16.0 / 14.0 m3/min ',
            DehumidifyingCapacity: '5.20L/h',
            PipeSize: '6.35mm / 15.88mm',
            DimensionIndoor: '1150 x 333 x 245 mm',
            DimensionOutdoor: '850 x 800 x 298 mm',
            WeightIndoor: '18kg',
            WeightOutdoor: '70kg'
        }
    },
    {
        acid: 7,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        inverter: true,
        type: 'Cooling All DC Inverter',
        model: 'RAS-SD10CD / RAS-SD13CD',
        capacity: '1.0 Ton',
        submodel: 'R410A',
        heating: false,
        system: 'Cooling',
        price: 48000,
        img1: 'https://i.ibb.co/fM7mLbN/7.png',
        img2: '',
        img3: '',
        features: [
            'Air Sleep',
            'All DC Inverter',
            'UV Fresh',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode Control',
            '3-Minute Delay Circuit (Fuse Blow Prevention)',
            'Auto Restart',
            'Changeable Drain Hose',
            'Pre filter',
            'Silent Mode',
            'Up-Down Auto Swing',
            'Anti-Rust Outdoor Casing',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1φ/50Hz/220-230V',
            Capacity: '3.50-3.52kW',
            TotalInput: '1,230-1,250W',
            TotalAmperes: '5.70-5.54A',
            EER: '9.72-9.62Btu/h.W',
            COP: '2.85-2.82',
            StartingCurrent: '27 A',
            AirFlow: '12.0/10.5/8.5/6.0 (HH/H/M/L/Sl)m3/min ',
            DehumidifyingCapacity: '2.8 l/h',
            PipeSize: '6.35/12.7mm',
            DimensionIndoor: '790 x 300 x 230 mm',
            DimensionOutdoor: '750 x 570 x 280 mm',
            WeightIndoor: '9.5kg',
            WeightOutdoor: '31.5kg'
        }
    },
    {
        acid: 8,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        inverter: true,
        type: 'Cooling All DC Inverter',
        model: 'RAS-DX18CF+RAC-DX18CF',
        capacity: '1.5 Ton',
        submodel: 'R410A',
        heating: false,
        system: 'Cooling',
        price: 65000,
        img1: 'https://i.ibb.co/YckdNxW/8.png',
        img2: '',
        img3: '',
        features: [
            'Air Sleep',
            'All DC Inverter',
            'UV Fresh',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode Control',
            '3-Minute Delay Circuit (Fuse Blow Prevention)',
            'Auto Restart',
            'Changeable Drain Hose',
            'Pre filter',
            'Silent Mode',
            'Up-Down Auto Swing',
            'Anti-Rust Outdoor Casing',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1Ø,50Hz,220-230V',
            Capacity: '5.20 (0.90-5.40)kW',
            TotalInput: '1,580 (355-2,200)W',
            TotalAmperes: ' 8.95-8.55A',
            EER: '11.2Btu/h.W',
            COP: '3.29',
            StartingCurrent: '8.95A',
            AirFlow: '15.0/14.5/13.0/9.0/6.5 (HH/H/M/L/S)m3/min',
            DehumidifyingCapacity: '2.8 l/h',
            PipeSize: '6.35/12.7mm',
            DimensionIndoor: '900 x 300 x 230mm',
            DimensionOutdoor: '750 x 570 x 280mm',
            WeightIndoor: '10kg',
            WeightOutdoor: '37kg'
        }
    },
    {
        acid: 9,
        brand: 'Hitachi',
        origin: 'Malaysia',
        installation: 'wall',
        type1: 'split',
        inverter: true,
        type: 'Cooling All DC Inverter',
        model: 'RAS-DX24CF+RAC-DX24CF',
        capacity: '2.0 Ton',
        submodel: 'R410A',
        heating: false,
        system: 'Cooling',
        price: 75000,
        img1: 'https://i.ibb.co/V9wnmdK/9.png',
        img2: '',
        img3: '',
        features: [
            'Air Sleep Sensor',
            'All DC Inverter',
            'UV Fresh',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Speed Cool',
            'Intelligent Fuzzy Logic',
            'Sleep Mode Control',
            '3-Minute Delay Circuit (Fuse Blow Prevention)',
            'Auto Restart',
            'Changeable Drain Hose',
            'Pre filter',
            'Silent Mode',
            'Up-Down Auto Swing',
            'Anti-Rust Outdoor Casing',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Super Wide Horizontal Louver',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1Ø,50Hz,220-230V',
            Capacity: '3504 kWh/yr',
            TotalInput: '1,960 (200-2,820)W',
            TotalAmperes: '9.00-8.60A',
            EER: '11.32Btu/h.W',
            COP: '3.32',
            StartingCurrent: '9A',
            AirFlow: '15.5/15.0/13.5/10.0/7.0 (HH/H/M/L/S)m3/min',
            DehumidifyingCapacity: '4.5 l/h',
            PipeSize: '9.35/15.88mm , Maximum Length/ Height : 30/20m',
            DimensionIndoor: '900x300x230mm',
            DimensionOutdoor: '850x800x298mm',
            WeightIndoor: '10kg',
            WeightOutdoor: '55kg'
        }
    },
    {
        acid: 10,
        brand: 'Hitachi',
        origin: 'China',
        installation: 'Ceiling',
        type1: 'split',
        inverter: false,
        type: 'Cooling Constant Model',
        model: 'RPFC-6.0TNZ1NH+RAS-6.0TNZGMH1',
        capacity: '4.0 Ton',
        submodel: 'R410A',
        heating: false,
        system: 'Cooling',
        price: 140000,
        img1: 'https://i.ibb.co/jrjYhKL/10.png',
        img2: '',
        img3: '',
        features: [
            'Low Ambient Cooling',
            'Low Ambient Heating',
            'High Efficiency Compressor',
            'UV Fresh',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Smart Defrost',
            'Intelligent Fuzzy Logic',
            'Sleep Mode Control',
            '3-Minute Delay Circuit (Fuse Blow Prevention)',
            'Auto Restart',
            'Changeable Drain Hose',
            'Pre filter',
            'Low Noise Vortex Fan & Fresh Air Inlet',
            '4-Way Airflow',
            'Anti-Rust Outdoor Casing',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Energy saving model.',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1Ø,50Hz,220-230V',
            Capacity: '43910 BTU.',
            TotalInput: '6479W',
            TotalAmperes: '12.1A',
            EER: '2.64',
            COP: '3.32',
            StartingCurrent: '8.8A',
            AirFlow: '2000/1800/1600 (HH/H/M/L/S)m3/h',
            DehumidifyingCapacity: '4.5 l/h',
            PipeSize: '50m',
            DimensionIndoor: '1300 x 350 x 800',
            DimensionOutdoor: '950 x 1050 x 340',
            WeightIndoor: '62kg',
            WeightOutdoor: '103kg'
        }
    },
    {
        acid: 11,
        brand: 'Hitachi',
        origin: 'China',
        installation: 'Ceiling',
        type1: 'split',
        inverter: false,
        type: 'Cooling Constant Model',
        model: 'RPFC-6.5TNZ1NH+RAS-6.5TNZGMH1',
        capacity: '4.5 Ton',
        submodel: 'R410A',
        heating: false,
        system: 'Cooling',
        price: 150000,
        img1: 'https://i.ibb.co/hRTYNpk/11.png',
        img2: '',
        img3: '',
        features: [
            'Low Ambient Cooling',
            'Low Ambient Heating',
            'High Efficiency Compressor',
            'UV Fresh',
            'Cooling Operation proved at 55℃',
            'Nano Titanium WASABI Air Purifying Filter',
            'Smart Defrost',
            'Intelligent Fuzzy Logic',
            'Sleep Mode Control',
            '3-Minute Delay Circuit (Fuse Blow Prevention)',
            'Auto Restart',
            'Changeable Drain Hose',
            'Pre filter',
            'Low Noise Vortex Fan & Fresh Air Inlet',
            '4-Way Airflow',
            'Anti-Rust Outdoor Casing',
            'Lambda Heat Exchanger (Energy Efficient)',
            'Green Fin Condenser',
            'Fireproof Electrical Enclosure',
            'Energy saving model.',
            'Super Wide Discharge Outlet'
        ],
        moreFeatures: [
            'DC Power System (Safe and Efficient)',
            'Tropical Model 55℃'
        ],
        sepcifications: {
            Phase: '1Ø,50Hz,220-230V',
            Capacity: '49860 BTU.',
            TotalInput: '6479W',
            TotalAmperes: '12.1A',
            EER: '2.64',
            COP: '3.32',
            StartingCurrent: '8.8A',
            AirFlow: '2000/1800/1600 (HH/H/M/L/S)m3/h',
            DehumidifyingCapacity: '4.5 l/h',
            PipeSize: '50m',
            DimensionIndoor: '1300 x 350 x 800',
            DimensionOutdoor: '950 x 1050 x 340',
            WeightIndoor: '62kg',
            WeightOutdoor: '103kg'
        }
    },
];
export default ac;


/* https://i.ibb.co/BgsWhvL/1.png
https://i.ibb.co/pfGGg8Q/2.png
https://i.ibb.co/vZKpbkG/3.png
https://i.ibb.co/ChGzSsJ/4.png
https://i.ibb.co/6Yvrx83/5.png
https://i.ibb.co/bgDFzPV/6.png
https://i.ibb.co/fM7mLbN/7.png
https://i.ibb.co/YckdNxW/8.png
https://i.ibb.co/V9wnmdK/9.png
https://i.ibb.co/p08tDfP/10.jpg
https://i.ibb.co/jrjYhKL/10.png
https://i.ibb.co/hRTYNpk/11.png */